name: Build HsMod

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: bepinex5

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HsMod-Release
        # 更新为准确的路径
        path: HsMod/Release/HsMod.dll
